### ISSUE TITLE
Nasadit na data.gov.cz jednoduchý redakční systém pro správu sekce Novinek a Článků - NETLIFY CMS

### ISSUE THREAD

**Issue by michalkuban** [opendata-mvcr/opendata-mvcr.github.io#105]
Současná verze Portálu otevřených dat neumožňuje jednoduché přidávání příspěvků do sekce NOVINKY a ČLÁNKY, čímž výrazně zpomaluje vydávání a publikaci novinek a článků pro úředníky ministerstva vnitra. MV ČR je tak závislé na externích spolupracovnících a projektech. 

Vlastní redakční systém pro Portál otevřených dat zrychlí přidávání článků, ale také zajistí, že přidat článek nebo novinku může bez problému přidat každý zaměstnanec veřejní správy bez složitého a nákladného školení. 

Pro nasazení redakčního systému bylo doporučeno https://www.netlifycms.org/, které zajišťuje jednoduchý redakční systém, který se napojí na POD na sekci Novinky a Články a autor příspěvku píše a edituje jako normálně v běžném prostředí dokumentu. Příspěvek se po pak jednoduše nahraje a zveřejní v požadované sekci.

**Comment by jakubklimek** [comment]
Nasazeno na http://pod-test.mvcr.gov.cz/admin. Výtvory jdou "publikací" do `develop` branche, tedy na http://pod-test.mvcr.gov.cz. Na data.gov.cz se dostanou klasickým PR z develop do master již mimo Netlify. Později lze konfiguraci změnit.
Poznatky:
- vložené obrázky jsou čistě markdownové, je třeba je tedy pro soulad s metodikou v rámci PR do masteru přepsat
- odkazy jsou čistě markdownové, je třeba je tedy pro soulad s metodikou v rámci PR předělat na reference-style
- datum novinky je vždy aktuální datum
