### ISSUE TITLE
Vložit monitoring návštěv ala Google Analytics pro sledování návštěnosti a aktivit na portálu

### ISSUE THREAD

**Issue by michalkuban** [opendata-mvcr/opendata-mvcr.github.io#16]
Je možno vložit Google analytics včetně lišty, že se sbírají data o aktivitě uživatele na portálu a že s tím uživatel po odkliknutí souhlasí.

**Comment by jakubklimek** [comment]
Ano. Tato lista je ovsem netrivialni - je treba se ptat na kazdy typ
sbírané informace zvlášť a umoznit souhlas kdykoliv odvolat. Na tuto
analyzu (jak toa vypadat a co toa delat) v soucasnosti nejsou kapacity.

**Comment by jakubklimek** [comment]
Bylo by třeba implementovat něco jako https://www.cookiebot.com/en/

**Comment by jakubklimek** [comment]
Dokud k tomuto nebude jasné stanovisko MVČR, můžeme zavřít.
