### ISSUE TITLE
Z e-learningu se nedá prokliknout "zpět na přehled kurzu"

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/opendata-mvcr.github.io#179]
Když procházím slidy, nemůžu "nahoru do rozcestníku modulů".
Tento odkaz bych dal jako proklik z log otevřených dat a esf.

**Comment by martinvita** [comment]
Určitě z těch log. Otázka je, jestli to nepřidat ("Zpět na kurz") ještě do patičky vpravo, aby se to zobrazovalo pod těmi navigačními šipečkami. Co myslíte?

**Comment by jakubklimek** [comment]
Tam by se to podle me pletlo s těmi šipkami. "Zpět" mi přijde že patří nahoru.

**Comment by martinvita** [comment]
OK, takže to bude jen na ta loga.

**Comment by skodapetr** [comment]
@martinvita není, tohle je čistě HTML na straně toho školení, je třeba to upravit v každém souboru - nakonec se žádných jekyll specifických věcí nepoužívalo.

**Comment by jakubklimek** [comment]
Nedávno jsem to na Jekyll layout předělal, takže by to mělo stačit upravit tam.
