### ISSUE TITLE
informace na úvodní stránce a závěrečné testy

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#180]
Na [úvodní stránce](https://opendata-mvcr.github.io/vzd%C4%9Bl%C3%A1v%C3%A1n%C3%AD/e-learning/) doporučuji upřesnit obecné informace o kurzu, např. doplnit vytučněné níže.

"Školení otevřených dat online je určeno k samostudiu bez lektora. K dispozici je pět kurzů, **přičemž u obecnějších kurzů jsou k dispozici detailní informace bez komentáře a u technických kurzů je prezentace obohacena výkladem. První dva kurzy jsou zakončeny závěrečným testem, po jejichž úspěšném splnění může účastník požádat o vystavení certifikátu o absolvování kurzu.**" 

Zároveň doporučuji zvážit, zda neudělat závěrečný test u všech kurzů, protože jinak nebudeme mít žádnou informaci o účastnících. Do textu bychom pak klidně mohli napsat, že ten test slouží i pro nás, abychom měli informaci o počtu účastníků, tak je prosíme, aby ho vyplnili a dali nám na sebe kontakt. U testů je nezbytné na začátku formuláře doplnit kontaktní údaje účastníků a souhlas se zpracováním údajů a s odebíráním novinek, např. jak je u přihlášení na online školení. Pokud by to tam nebylo, tak bude velmi problematické určit, kdo kdy dělal jaký test.

**Comment by jakubklimek** [comment]
Text jsem upravil podle návrhu.

Co se týče testů u ostatních školení, to je asi na zvážení @dchocholaty a @martinnec .

**Comment by RadkaDomanska** [comment]
Ještě k tomu závěrečnému testu. Vyplnila jsem test ke kurzu Co jsou otevřená data a ani se mi neukázalo, zda jsem odpověděla správně/špatně, což mi nepřijde úplně OK. Zobrazila se mi jen informace, že odpověď byla zaznamenána, ale nechtělo to po mě žádné údaje (jméno, organizaci, atd), tak nevím, co se vám tam zaznamenalo. Šlo by nastavit, aby účastník viděl alespoň počet správných odpovědí a umožnili jsme mu na otázky, které má špatně odpovědět znovu?

**Comment by jakubklimek** [comment]
To asi souvisí s tím, že to je Google Form - tedy to není řešení na testování a tyhle věci tam zřejmě nepůjdou.

**Comment by RadkaDomanska** [comment]
hmm, to je škoda že takové věci přes google form nejdou. A nemáte někdo nápad, jak by to šlo udělat jinak? Trochu se bojím, že nám pak budou chodit desítky emailů od úředníků, kteří se budou ptát, jak dopadli že dělali test 11.8. v 13:28. Jinak mě ještě napadlo dát na konec testu i text. pole, kde nám mohou dát zpětnou vazbu ke školení. Nebo by to klidně mohl být i samostatný formulář, kde se budeme ptát např. jak se jim školení líbilo (škála), jestli jim vyhovovala online forma, co se nového naučili, co bychom měli změnit/doplnit, 3 hlavní myšlenky, které si z kurzu odnáší, atd. Toto je velmi cenná zpětná vazba, která nám může pomoct při tvorbě dalších školení.

**Comment by jakubklimek** [comment]
No, co já si pamatuju, tak jsme se bavili o tom, že na konci kurzu řekneme, že kdo chce certifikát, má se ozvat mailem, bude mu pak zaslán link na test, který zašle vyplněný, a na základě toho bude vystaven certifikát, tedy že to celé bude manuální proces.

Tedy pro mne byla novinka to, že jsou testy pomocí Google Forms - ale asi se neúčastním všech debat, takže mi to možná jen uteklo.

**Comment by RadkaDomanska** [comment]
No, já už si taky úplně nepamatuju, na čem jsme se domluvili, ale aktuální stav mi nepřijde úplně OK, tak bychom to možná mohli probrat. Asi bych si dovedla představit, že by na konci každého kurzu byl odkaz na google form, kde nám mohou dát zpětnou vazbu a upsat se k odběru novinek ze světa OD. A ten test by se asi dal pořešit až na dotaz na mail OD, když to jinak neumíme, ale bude to teda administrativní pruda.

**Comment by jakubklimek** [comment]
Testy byly přidány.
