### ISSUE TITLE
text zasahující do zápatí

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#182]
na [stránce kurzu co jsou otevřená data](https://opendata-mvcr.github.io/vzd%C4%9Bl%C3%A1v%C3%A1n%C3%AD/e-learning/co-jsou-otev%C5%99en%C3%A1-data/co-jsou-to-otev%C5%99en%C3%A1-data/#/1/0/0) se překrývá text se zápatím
![překryv textu](https://user-images.githubusercontent.com/73894642/128865478-e8558177-9a93-40b7-9c8b-e1d0be59e77e.jpg)

**Comment by skodapetr** [comment]
Tohle je první bod u mého komentáře v #177.
