### ISSUE TITLE
upřesnění co znamená snadná dostupnost

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#184]
Na [slidu](https://opendata-mvcr.github.io/vzd%C4%9Bl%C3%A1v%C3%A1n%C3%AD/e-learning/co-jsou-otev%C5%99en%C3%A1-data/co-jsou-to-otev%C5%99en%C3%A1-data/#/13/0/0) je uvedeno, že OD musí být snadno dostupná.  Nerozumím, co snadná dostupnost znamená a z čeho vychází, není vysvětleno. Nestačila by pouze dostupnost, resp. dostupná ke stažení bez technických překážek (registrace, omezení počtu přístupů, CAPTCHA, apod.), případně jen ta strojová čitelnost (dle § 3 odst. 7 formát datového souboru s takovou strukturou, která umožňuje programovému vybavení **snadno** nalézt, rozpoznat a získat z tohoto datového souboru konkrétní informace)?

**Comment by martinvita** [comment]
Co kdybychom tam dali _"dostupná na internetu bez technických a jiných překážek (registrace, omezení počtu přístupů, ...)"_
Dal bych tam "na internetu" (což stejně musí být kvůli registraci na NKOD), aby nevznikala otázka, jestli registrace je technická překážka, tak bych tam dal formulaci "technických a jiných". Co o tom soudíte?

**Comment by RadkaDomanska** [comment]
jako "na internetu" ani "jiných překážek" mi nevadí, ale není tam důležité hlavně to "ke stažení"?

**Comment by martinvita** [comment]
Dejme tam tedy i ke stažení, já se přiznávám, že jsem lavíroval nad tím, jestli tam nedat i "prohlížení", nakonec jsem tam nedal nic, ale dáme tam to stažení.
Čili výsledek: _"dostupná na internetu ke stažení bez technických a jiných překážek (registrace, omezení počtu přístupů, ...)"_
