### ISSUE TITLE
příklady metadat datové sady

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#188]
Na [slidu](https://opendata-mvcr.github.io/vzd%C4%9Bl%C3%A1v%C3%A1n%C3%AD/e-learning/co-jsou-otev%C5%99en%C3%A1-data/katalogizace-otev%C5%99en%C3%BDch-dat/#/6/0/0) jsou uvedeny příklady metadat. IMHO je pro představu důležitý i název, popis a poskytovatel - navrhuji doplnit do výčtu.

**Comment by martinvita** [comment]
Při této příležitosti odstraním nesystémové použití spojení "datové sady" – z kontextu je to jasné a navíc to nebylo konzistentní (u některých položek to bylo, u některých ne).
