### ISSUE TITLE
nejasná věta

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#197]
Na [slidu](https://opendata-mvcr.github.io/vzd%C4%9Bl%C3%A1v%C3%A1n%C3%AD/e-learning/publika%C4%8Dn%C3%AD-pl%C3%A1n-a-publikace-dat/%C3%BAvod-do-kurzu/#/3/0/4) je uvedeno "ukazuje vedení stav dat vedených v jejich IT systémech.". Nemělo by tam být "ukazuje vedení organizace stav.."? Resp. si říkám, jestli je nutné to vedení, protože, když ho zveřejní, tak to ukazuje všem. A taky přemýšlím, jestli je to pravda, že to ukazuje stav dat vedených v IS. Asi bych tu odrážku raději odstranila, případně to prosím nějak upřesněte.

**Comment by martinvita** [comment]
@RadkaDomanska To vedení tam nutné asi není, máte pravdu, že to říká všem, kdo jsou adresáti publikačního plánu (čili v případě jeho zveřejnění "všichni"). Ono se to tam dostalo nějak při připomínkování černých slidů.
Můžeme to vypustit, nicméně já bych navrhoval dát tam následující odrážku:

- odráží stav dat vedených v jejich IT systémech z perspektivy otevřených dat

Co o tom soudíte...? Prostě ten publikační plán nějakým způsobem ukazuje, jaký je stav jejich dat z hlediska otevřenosti.

**Comment by RadkaDomanska** [comment]
Ok, tak to nechte,  jak navrhujete :)
