### ISSUE TITLE
úprava řezu písma

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#201]
Na [slidu](https://opendata-mvcr.github.io/vzd%C4%9Bl%C3%A1v%C3%A1n%C3%AD/e-learning/publika%C4%8Dn%C3%AD-pl%C3%A1n-a-publikace-dat/role-v-procesu-otev%C3%ADr%C3%A1n%C3%AD-dat-v-organizaci/#/18) je poslední věta kurzívou, má to nějaký důvod? Neměly by být všechny tři věty stejně?

**Comment by martinvita** [comment]
Záměr byl, že to bude chápáno jako takové doplnění, něco co by bylo jinak v závorce. Ale mohu do samozřejmě změnit, nijak na tom nelpím.

Jinak, moc se mi líbí to názvosloví "řez písma"! Jsem pro používání téhle terminologie, stejně jako "stupeň písma", namísto "velikost písma". Typografové budou jásat!
