### ISSUE TITLE
upřesnění jaké vedení

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#207]
Na [slidu](https://opendata-mvcr.github.io/vzd%C4%9Bl%C3%A1v%C3%A1n%C3%AD/e-learning/publika%C4%8Dn%C3%AD-pl%C3%A1n-a-publikace-dat/vytvo%C5%99en%C3%AD-publika%C4%8Dn%C3%ADho-pl%C3%A1nu-a-jeho-%C5%BEivotn%C3%AD-cyklus/#/7) doporučuji upřesnit, že jde o vedení **organizace**.

**Comment by martinvita** [comment]
Týká se to více slidů v tomto modulu, bude upraveno u všech výskytů.
