### ISSUE TITLE
Změna fontu

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#209]
Dávám ke zvážení, zda neupravit font písma v zápatí (název a číslo projektu). Trochu mi trhá oči, že vše na slidu je bezpatkovým písmem a číslo projektu je patkovým. Ale netrvám na tom, pokud se to ostatním zdá OK, tak to překousnu :).

**Comment by skodapetr** [comment]
@jakubklimek  A na co by ta změna měla být ?

**Comment by jakubklimek** [comment]
Nejlépe na stejné nastavení jako zbytek webu, tedy viz bootstrap:
```css
--bs-font-sans-serif: system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans","Liberation Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
```

**Comment by jakubklimek** [comment]
V souvislosti s reportovanym problemem s nekterymi ceskymi znaky sjednotime pismo na slidech s pismem vsude na POD
