### ISSUE TITLE
rozlišovat věty a odrážky

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#210]
Připomínka od Radan Březa (NAKIT):
Je třeba rozlišovat mezi větou, která má podmět, přísudek, předmět, začíná velkým písmenem a končí tečkou, od hesel s odrážkami. Obě varianty je možné používat, ale není vhodné je míchat.

**Comment by martinvita** [comment]
Dohodnuto, že v současné době nebudeme řešit. Drobné úpravy budou provedeny v rámci jiných issues.
