### ISSUE TITLE
doplnit k modulům, co jsme se naučili

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#212]
Připomínka od Radan Březa (NAKIT):
•	Podobná školení obvykle na začátku kapitoly definují, o čem kapitola bude. Na konci udělají shrnutí, co jsme se v kapitole dověděli.

**Comment by martinvita** [comment]
Po dohodě nebudeme řešit – rozsah jednotlivých modulů není tak velký, aby to bylo nutností. Spíše by šlo v tomto ohledu o zbytečnou rekapitulaci na konci každého modulu.
