### ISSUE TITLE
upřesnění typu organizací

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#213]
Připomínka od Radan Březa (NAKIT):
•	Chybělo mě tam informace, že se bavíme o datech vznikajících ve státní správě a možná některých polo(státních) organizací typu zdravotní pojišťovny. Tedy že zde nejsou data státních podniků (ČEZ, ČD), ani komerčních firem

**Comment by martinvita** [comment]
Po dohodě nebudeme v současné době řešit, mj. proto, že sada institucí, které mohou publikovat/registrovat se do NKOD, se bude rozšiřovat.
