### ISSUE TITLE
nepoužívat negaci v nadpisech

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#215]
Připomínka od Radan Březa (NAKIT):
•	Nadpis „NEOMEZUJÍCÍ PODMÍNKY UŽITÍ“  není optimální. Nadpisy obsahující negaci bývají pro čtenáře matoucí.

**Comment by martinvita** [comment]
V tomto konkrétním případě jde o zaužívaný pojem – "terminus technicus", proto necháme v současném stavu, abychom byli konzistentní.
