### ISSUE TITLE
pojem datové schéma

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#219]
Připomínka od Radan Březa (NAKIT):
•	Pojem „Datové schéma“ se mě nelíbí.  Použil bych pojem „datový model“, ale to může být osobní, ovlivněné moji mnohaletou prací s databázemi.

**Comment by jakubklimek** [comment]
Záleží, v jakém kontextu. Pokud je myšleno vyjádření omezení na obsah konkrétního souboru (XSD, JSON Schema, CSV on the Web descriptor), pak je to datové schéma. Pokud jde o "sadu nástrojů pro reprezentaci dat nějakým způsobem", tj. uzly a hrany, nebo tabulky s řádky a sloupci, nebo elementy a jejich atributy - pak je to datový model. Dále viz [technické aspekty](https://docs.google.com/presentation/d/1iQ14oBCQxBrhmj0L_017kbxi4LRMvKIcNkjEmeLrpB4/edit#slide=id.gb83163cf02_0_135) ;)
