### ISSUE TITLE
snížení počtu zmínění "barevných" excelů

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#220]
Připomínka od Radan Březa (NAKIT):
•	Zmínka o „barevném excelu“ se ve školení objevuje několikrát, možná až zbytečně.

**Comment by martinvita** [comment]
Já bych osobně to množství zmínek o "barevném excelu" nesnižoval. Osobně si myslím, že pokud to tam tak nějak vyčnívá (díky čemuž si toho asi pan Březa všiml), tak je to spíš dobře, protože pokud si absolvent odnese z kurzu mj. ponaučení, že "barevný excel je mor", tak to bude fajn :-) Jaký je na to váš názor – @RadkaDomanska ?

**Comment by RadkaDomanska** [comment]
souhlas, nechte to tam, nemusíme vyhovět všemu

**Comment by martinvita** [comment]
@RadkaDomanska děkuju, necháme to tedy tak. Možná pro další generace elearningu to bude podnět, každopádně nyní uzavírám.
