### ISSUE TITLE
upřesnění pojmu OFN

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#222]
Připomínka od Radan Březa (NAKIT):
•	Pojem „Otevřené formální normy“ je pojem mezinárodně  uznávaný, nebo je to výmysl zákona 106/1999. Chtělo by zdůraznit, jak to je.

**Comment by martinvita** [comment]
@jakubklimek @martinnec – neznám historii pojmu OFN, předpokládám, že to má nějaký mezinárodní přesah. Z čeho to, prosím, vychází?

**Comment by jakubklimek** [comment]
Viz https://eur-lex.europa.eu/legal-content/CS/TXT/?uri=CELEX:32019L1024

**Comment by jakubklimek** [comment]
Já bych asi neříkal "mají oporu", protože ten pojem otevřená formální norma pochází z té směrnice
