### ISSUE TITLE
vyplňující věty

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#225]
Připomínka od Radan Březa (NAKIT):
•	Když člověk školí naživo tak používá řadu pomocných vět a otevřených otázek, na které v textu není prostor. Například větička: „Řešení si prozradíme na dalším slide…“ nebo „Dospěli jste také k tomuto výpisu?“

**Comment by RadkaDomanska** [comment]
já bych řekla,  že je chce dát pryč... ale klidně mu napište,  jak to myslel na Radan.Breza@nakit.cz

**Comment by martinvita** [comment]
@RadkaDomanska Já jsem také nezávisle na vás tipoval, že je chce dát pryč. Já je pryč dám, resp. zakomentuji. Fakt je, že tenhle styl se tam objevuje jen v podstatě na jednom místě. Kdyby byla poptávka, tak by asi bylo dobré to pak doplnit do celého.
