### ISSUE TITLE
zobrazování slidů uživatelsky nepřívětivé

### ISSUE THREAD

**Issue by hruskamart** [opendata-mvcr/opendata-mvcr.github.io#228]
Považuji za uživatelsky nepřívětivé zobrazování jednotlivých položek na slidu po stisku klávesy/kliknutí. Zcela nevhodné mi to přijde, v situaci, kdy se chci vrátit o pár slidů zpět a musím znovu všechny položky tzv. "odklikat".

Považuji za vhodnější, aby se slidy zobrazovali celé a nikoliv po jednotlivých odrážkách.

**Comment by martinvita** [comment]
Na základě dohody uzavírám s tím, že v tuto chvíli nebudeme řešit. Drobné úpravy odkrývání budou provedeny v rámci dalších issues.
