### ISSUE TITLE
doplnění časové náročnosti/předpokládané doby studia

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/opendata-mvcr.github.io#229]
Doporučuji na úvodní stránku každého kurzu do popisu doplnit časovou náročnost/předpokládanou dobu studia daného kurzu. IMHO by se to hodilo do části struktura kurzu, aby účastníci měli představu, kolik času jim to zabere. 
Ve slidech kurzu Co jsou otevřená data i Publikační plán a publikace dat je uvedena předpokládaná doba studia kurzu 2,5 hod. Videa u kurzu Katalogizace otevřených dat mají dohromady 0:24:40
Videa u kurzu Úvod do otevřených formálních norem mají dohromady 1:49:07
Videa u kurzu Technické aspekty otevřených dat mají dohromady 1:46:37

U namluvených kurzů by v této časti mohla být doplněna ještě věta: _Jednotlivé moduly jsou k dispozici formou videí, které lze spustit kliknutím na pole "YouTube". Prezentace s komentářem jsou dostupné i v textové podobě a lze je zobrazit kliknutím na pole "Google Slidy"._

**Comment by jakubklimek** [comment]
Tu větu jsem tam přidal.
U časů je ale trochu problém, že součástí mluvených kurzů jsou i opakovací slidové. Tedy bych to tak nějak odhadl a řekl že Katalogizace je 45 minut, OFN 2h a technické aspekty také 2h?

**Comment by martinvita** [comment]
Pokud k tomu bude ještě i nějaký ten "GoogleTestík", tak by stálo za to k tomu přidat i nějakou časovou dotaci na něj...

**Comment by RadkaDomanska** [comment]
za mě souhlas s navrženými časy, stejně je to jen orientační :)

**Comment by jakubklimek** [comment]
Přidal jsem tedy časy i do [přehledu e-learningových kurzů](https://opendata-mvcr.github.io/vzdělávání/e-learning/).
