### ISSUE TITLE
Nefunkční odkazy v článcích "Série Znalostní grafy"

### ISSUE THREAD

**Issue by bornedan** [opendata-mvcr/opendata-mvcr.github.io#279]
V článku [https://data.gov.cz/%C4%8Dl%C3%A1nky/znalostn%C3%AD-grafy-03-sparql](https://data.gov.cz/%C4%8Dl%C3%A1nky/znalostn%C3%AD-grafy-03-sparql) se jako s příkladem pracuje s datovou sadou [https://data.gov.cz/zdroj/datov%C3%A9-sady/http---vdb.czso.cz-pll-eweb-package_show-id-290038r19](https://data.gov.cz/zdroj/datov%C3%A9-sady/http---vdb.czso.cz-pll-eweb-package_show-id-290038r19) která vede na neexitující stránku. Nevím zda se změnila adresa datové sady nebo již je nepřístupná, ale ani v jednom případě nefunguje. Rozumím že články jsou již staršího data a nebudou aktuální věčně, tak na to alespoň upozorňuju.

**Comment by jakubklimek** [comment]
Díky za upozornění. Dotžená datová sada má nyní IRI `https://data.gov.cz/zdroj/datové-sady/00025593/719f7b9f2cf4ab7fa40c7e7c459995a7` poté, co ČSÚ přešlo na nový lokální katalog. Článek upravíme.

**Comment by bornedan** [comment]
Díky, ještě upozorním, že se chyba vyskytuje ve všech třech dílech seriálu.
