### ISSUE TITLE
Vyhláška o přístupnosti č 64/2008 na patičce webu je neaktuální 

### ISSUE THREAD

**Issue by michalkuban** [opendata-mvcr/opendata-mvcr.github.io#40]
Vyhláška č. 64/2008 Sb., o formě uveřejňování informací souvisejících s výkonem veřejné správy prostřednictvím webových stránek pro osoby se zdravotním postižením (vyhláška o přístupnosti) je neaktuální a odkazuje na zakony pro lidi (https://www.zakonyprolidi.cz/cs/2008-64) s tím, že je k datu **09.04.2019 zrušena.**

**Comment by jakubklimek** [comment]
Ano, a na stejně neaktuální vyhlášku se odkazuje i [gov.cz](https://gov.cz/prohlaseni-o-pristupnosti/). Jsme schopni někde získat vyhovující text?

**Comment by jakubklimek** [comment]
Dle [aktuálních informací](https://www.mvcr.cz/clanek/pristupnost-internetovych-stranek-a-mobilnich-aplikaci.aspx?q=Y2hudW09OA%3d%3d) máme do 22.9.2020 toto vyřešit.
