### ISSUE TITLE
Špatná IRI OVM z RPP

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/opendata-mvcr.github.io#47]
OVM jsou v RDF datech NKOD pomocí owl:sameAs vázány na IRI ve tvaru http://szrcr.cz/odrpp/zdroj/orgán-veřejné-moci/00007064  . To je ale starý tvar platný v době návrhu LOD z RPP. Aktuálně platí tvar https://rpp-opendata.egon.gov.cz/odrpp/zdroj/orgán-veřejné-moci/00007064

**Comment by jakubklimek** [comment]
Fixed
