### ISSUE TITLE
Špatná IRI adresních míst v RDF NKOD

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/opendata-mvcr.github.io#49]
V adresních místech v RDF NKOD je tvar https://linked.cuzk.cz/resource/ruian/adresni-mista/25852213, ale má být https://linked.cuzk.cz/resource/ruian/adresni-misto/25852213 . Resp. CUZK první tvar nepřesměrovává, druhý ano.

**Comment by jakubklimek** [comment]
Bylo to v XSLT v Seznamu OVM - opraveno.
