### ISSUE TITLE
Stránka s úkony RPP má problémy s přístupností na mobilech

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/opendata-mvcr.github.io#50]
https://data.gov.cz/datové-články/registr-práv-a-povinností/rpp-úkony.html

Potřebujeme stránku upravit tak, aby splňovala základní pravidla formátování pro zbytek webu. Aktuálně kvůli ní chodí errory od Googlu.

**Comment by martinnec** [comment]
Je tohle ještě aktuální? Lze to úplně vymazat, bude to napsané úplně jinak v rámci nové KG série.
