### ISSUE TITLE
V IE11 nefunguje zobrazování počtu datových sad a poskytovatelů 

### ISSUE THREAD

**Issue by michalkuban** [opendata-mvcr/opendata-mvcr.github.io#8]
V IE 11 nefunguje zobrazování aktuálního počtu datový sad. Viz obrázek 

![iedata](https://user-images.githubusercontent.com/8858125/43071285-98316fd6-8e72-11e8-844c-94ec10a863ff.PNG)

**Comment by jakubklimek** [comment]
Ano, IE11 není podporován. Aktuální verze je prohlížeče od MS je Edge.

**Comment by jakubklimek** [comment]
Já jim řikám vždycky ať prohlížej web v něčem slušnym, tzn. Firefox, Chrome, Safari, Opera, a když už musej od MS, tak aktuální.

**Comment by michalkuban** [comment]
Já s Tebou souhlasím, ale taky říkám, že ne vždycky jim to zaměstnavatel, resp. jejich ajťák povolí a "slušný" prohlížeč je při ruce.

**Comment by jakubklimek** [comment]
Ja ti taky rozumim. Je to ale takto:
IT slouží zaměstnancům. Zaměstnanec chce/potřebuje používat něco, co mu jeho IT vybavení neumožňuje => řekne svému IT "zařiď to" a to to zařídí. Pokud ne, tak ho IT blokuje v jeho práci. Takto je to správně.

Přeci se nebude přizpůsobovat každá webová stránka, kterou může potenciálně navštívit úředník, x let starým technologiím, protože "přeci víme jak to na úřadech chodí". Takhle by se nikdy nic nezměnilo.

Máme tedy s tímto problémem někoho konkrétního komu je to třeba vysvětlit, a nebo to zkoušíš jen tak pro jistotu?

**Comment by michalkuban** [comment]
Nahlásil jsem chybu, která je způsobena, tím že mám starý prohlížeč. Vysvětlil jsi mi to. Konkrétní osoba, která si na to stěžovala není.

**Comment by jakubklimek** [comment]
Konkrétně tedy jde o to, že IE11 nepodporuje [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). Samozřejmě by to šlo udělat, ale s netriviálním úsilím, které do podopory zastaralých technologií nechceme investovat, pokud to z nějakého důvodu nebude nezbytně nutné.
