### ISSUE TITLE
Nefungující odkazy v článku o hackathonech 

### ISSUE THREAD

**Issue by michalkuban** [opendata-mvcr/opendata-mvcr.github.io#82]
V článku na Portálu otevřených dat o [hackathonem 2019](https://data.gov.cz/články/hackathony-2019 ) jsou následující:  

- nefungující odkazy na legislativu [ ]  
![Screenshot 2020-04-24 at 10 35 05](https://user-images.githubusercontent.com/8858125/80192423-73007100-8617-11ea-9455-7ab1375e9fac.png)

- neaktivní odkaz  [ ]
![Screenshot 2020-04-24 at 10 37 48](https://user-images.githubusercontent.com/8858125/80192612-bd81ed80-8617-11ea-89a4-cadb75f9ce60.png)

- hranatá závorka v odkaze prvního URL [ ] 
![Screenshot 2020-04-24 at 10 39 45](https://user-images.githubusercontent.com/8858125/80192759-f91cb780-8617-11ea-81d3-68c93fe5ff52.png)

- nefungující odkazy na Smart Health [ ]
![Screenshot 2020-04-24 at 10 41 12](https://user-images.githubusercontent.com/8858125/80192912-341eeb00-8618-11ea-81e5-242fdf017f5b.png)
![Screenshot 2020-04-24 at 10 41 07](https://user-images.githubusercontent.com/8858125/80192913-35501800-8618-11ea-880f-756476e5f7bf.png)

- nefungující odkaz [ ] 
![Screenshot 2020-04-24 at 10 46 20](https://user-images.githubusercontent.com/8858125/80193317-dd65e100-8618-11ea-8bd2-8fbb6b6f43db.png)

**Comment by jirkamarekbrno** [comment]
@jakubklimek @michalkuban opraveno, díky za to. Byli tam překlepy v těch [lincích].

**Comment by jirkamarekbrno** [comment]
@jakubklimek můžu to tady uzavřít sám, nebo to taky uzavíráš ty? Díky

**Comment by jirkamarekbrno** [comment]
jo a @jakubklimek ověřoval jsem to i přes jekyll, že to funguje:)

**Comment by jakubklimek** [comment]
@jirkamarekbrno tady to zavre @michalkuban az to bude venku. Ten PR co sis mergnul jsem revertnul, takze to zkus znova a spravne, tzn. cerstvy fork z developu... vsak to znas.

**Comment by jirkamarekbrno** [comment]
@jakubklimek máš to tam k mergnutí:). díky.

**Comment by jakubklimek** [comment]
https://pod-test.mvcr.gov.cz/články/hackathony-2019

**Comment by michalkuban** [comment]
- [ ] Smazat tuto větu nebo ji opravit do minulého času:  _Letos se zapojilo již 21 partnerů._ 

- [ ] Přepsat do minulého času následující větu. - _Zajímavostí je poté i zapojení Technologické agentury ČR, která poskytla svá data o výzkumu._"

- [ ] Oprava hlavní **témata** hackathonu **byla** - 

- [ ] Chtěli navíc. "Pokud byste **chtěli** potřebovali bližší konzultaci, neváhejte nám napsat na emailovou adresu otevrenadata@mvcr.cz a do předmětu zprávy dát “hackathony”.

**Comment by jirkamarekbrno** [comment]
@jakubklimek @michalkuban opraveno, díky za podněty. J

**Comment by jakubklimek** [comment]
@jirkamarekbrno jen u tebe. musis udelat PR

**Comment by jakubklimek** [comment]
@michalkuban ok?
